05:45:55 PM: DEBUG [conexion.py:21] Conexi√≥n abierta exitosamente:user=postgres dbname=test_db host=localhost hostaddr=127.0.0.1 sslcertmode=allow
